#!/usr/bin/env node

const app = require('../app.json');
const dot = require('dot-object');
const fs = require('fs');
const spawn = require('child_process').spawn;

function Setup() {
  this.remoteConfig = {};
  try {
    this.localConfig = require('../config/local.js');
  } catch (e) {
    this.localConfig = {};
  }
}

Setup.prototype.mergeConfig = function mergeConfig() {
  for (var env in app.env) {
    if (!app.env[env].local) continue;
    dot.str(app.env[env].local, this.remoteConfig[env], this.localConfig);
  }
};

Setup.prototype.getRemote = function getRemote() {
  const heroku = spawn('heroku', ['config', '--json', `--app=${app.appName}`]);

  return new Promise((resolve, reject) => {
    heroku.stdout.on('data', config => {

      if (config.indexOf('Enter your Heroku credentials') !== -1) {
        console.error('You must log in to Heroku Toolbelt first.');
        return reject();
      }

      config = JSON.parse(config.toString());
      if (!config) {
        console.error('Unable to authenticate to Heroku.');
        return reject();
      }

      this.remoteConfig = config;
      this.mergeConfig();
      resolve(this.localConfig);
    });

    heroku.on('error', () => {
      console.warn('The Heroku CLI client does not appear to be installed.');
      console.warn('https://toolbelt.heroku.com');
      reject();
    });
  });
};

Setup.prototype.writeConfig = function writeConfig(config) {
  var localConfig = require('path').resolve(__dirname, '../config/local.js');
  fs.writeFileSync(localConfig, `module.exports = ${JSON.stringify(config, null, 2)}`);
  console.log('Local configuration has been saved.');
};

Setup.prototype.cloneDb = function cloneDb() {
  if (!this.localConfig.connections)
    return console.warn('A local database connection must be defined.');

  const dump = spawn('mongodump', [
    '--archive=databaseProd.archive',
    `--db=${app.database.db}`,
    `--host=${app.database.host}`,
    `--username=${app.database.user}`,
    `-p${this.remoteConfig[app.database.password]}`,
    '--excludeCollection=system.users'
  ]);

  dump.on('exit', code => {
    if (code !== 0)
      return console.warn('Archive of Production database failed...');

    const restore = spawn('mongorestore', [
      '--archive=databaseProd.archive',
      `--host=${this.localConfig.connections.local.host}:${this.localConfig.connections.local.port}`,
      '--drop'
    ]);
    restore.on('exit', () => console.log('Production database copied to local.'));
    dump.on('error', () => console.warn('mongorestore does not appear to be installed.'));
  });

  dump.on('error', () => console.warn('mongodump does not appear to be installed.'));
};

var setup = new Setup();
setup.getRemote().then(config => {
  setup.writeConfig(config);
  setup.cloneDb();
});
