#!/usr/bin/env node
var start = new Date().getTime();
var program = require('commander').usage('<input>').parse(process.argv);
var worker = require(`./${program.args[0]}`);
var tripwire = require('tripwire');

process.on('uncaughtException', function(err) {
  console.error('WORKER: Event loop blocked for longer than 100 seconds.');
  console.error(err);
  process.exit(1);
});

tripwire.resetTripwire(100000);

var Sails = require('sails');
Sails.load({
  environment: 'production',
  hooks: {
    blueprints: false,
    csrf: false,
    cors: false,
    grunt: false,
    i18n: false,
    request: false,
    responses: false,
    session: false,
    views: false
  },
  log: {
    level: 'verbose'
  }
}, function(err, sails) {
  worker.run(function() {
    var end = new Date().getTime();
    sails.log.info(`[machine:${program.args[0]}] ${end - start}ms.`);
    process.exit();
  }, program.args[1]);
});
